### ISSUE TITLE
Add Gutenberg v. 3.5+ support

### ISSUE THREAD

**Issue by jomurgel** [WebDevStudios/WDS-Blocks#64]
Gutenberg v. 3.5+ breaks some blocks. Needs testing and updates for all blocks.

**Comment by efuller** [comment]
I started looking into this today.

I pushed a branch, but no commits as of yet: https://github.com/WebDevStudios/WDS-Blocks/tree/feature/%2364-support-for-3-7-0

I upgraded my local Gutenberg to `3.7.0`.

The image and video background options do not work globally. There is no button being supplied to upload/set a file:

https://d.pr/i/Z1YHio

https://d.pr/i/98mBHY

Other than the issue above, the following blocks look to be in working order:
- Call to action
- Default
- Github Gist
- Hero

The rest of the blocks do not seems to show up for selection. This is most likely due to some console errors.

It looks like `withAPIData` has been deprecated. As best I can tell, we will now need to use `withSelect`. You can find documentation on it here: 

https://wordpress.org/gutenberg/handbook/blocks/creating-dynamic-blocks/
https://github.com/WordPress/gutenberg/issues/7390 ( for more context )
