### ISSUE TITLE
WDS Blocks 2.0: Accordion Block

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wds-blocks#78]
Need to replicate the ACF Accordion Block functionality, but with a native block. Please use the `feature/block-2.0` branch as a base.

**Comment by coreymcollins** [comment]
## User Stories

As a site admin, I want to be able to select a background color using core Color Settings options so that the color is displayed as the background of the block.

As a site admin, I want to be able to upload an image in the Block Settings Panel so that the image is displayed as the background of the block.

As a site admin, I want to be able to upload a video in the Block Settings Panel so that the video is displayed as the background of the block.

As a site admin, I want to be able to set the font color using core Color Settings options so that I can ensure the block text is readable when displayed over its background element.

As a site admin, I want to be able to toggle on or off an option so that the first accordion item is expanded or collapsed when the block is first loaded.

As a site admin, I want to be able to add a block title so that it is displayed as the block title above the accordion items.

As a site admin, I want to be able to add text so that it is displayed as the block content above the accordion items.

As a site admin, I want to be able to add a repeatable group for accordion content so that I can add multiple accordions to the block.

As a site admin, I want to be able to add an accordion title so that it is displayed as the trigger button to expand and collapse the accordion.

As a site admin, I want to be able to add accordion text so that it is displayed for an accordion item when the accordion is expanded.

As a user, I want to be able to click or tape the accordion title so that the accordion content is expanded below the title.

As a user, when I expand one accordion item I want any other open accordion item to close so that I am only viewing the content for one accordion item at a time.

**Comment by dcooney** [comment]
@coreymcollins @gregrickaby

My initial high level thinking is the accordion functionality would actually consist of two blocks. 

### **`Accordion Group`** (parent)
- This block contains the block settings (bkg color, bkg image, title, desc etc.)
- Site admins add this block to the page and then using `InnerBlocks` they add nested `Accordion` blocks - no other block types are allowed. 
- When an `Accordion Group` is added to the page, auto-populate the `InnerBlocks` with a default `Accordion` to get them started.

### **`Accordion`** (child)
- This block that contains the expand/collapse content of an individual accordion.
- Can be added to the `Accordion Group Block` or directly to the block editor.
- Being able to add an accordion without the container and settings may be useful for some projects/clients that require a simple expand/collapse toggle.

I currently have an accordion block prototyped but want to gather consensus on this approach before I go any further and create the parent/child relationship.

**Comment by gregrickaby** [comment]
@dcooney This approach sounds good to me!

**Comment by salcode** [comment]
@dcooney I just watched your demo in the team meeting, it is looking awesome!

One thought about naming, I think "Accordion Group" and "Accordion" are a little confusing (naming things is always hard). I'd consider the following name changes:

- `Accordion Group` => `Accordion`
- `Accordion` => `Collapsable Section`

I think that might make it clearer when a Collapsable section is used outside the context of the Accordion (Group).

This is a very small UI thing, overall the code you demoed is amazing!

**Comment by dcooney** [comment]
@salcode agreed, it's confusing how it is now. I do feel `Accordion`(singular) is also confusing for a group of collapsable sections.

**Comment by salcode** [comment]
@dcooney Personally, I think `Accordion` (even though it is singular) is appropriate for referring to a collection of collapsable sections because it is analogous to the accordion musical instrument (with multiple collapsable sections in the bellows).

![image](https://user-images.githubusercontent.com/5194588/91311731-6a64a680-e781-11ea-9c90-100cd3d7acf8.png)

And yes, I did have to lookup the word "bellows" 😀

**Comment by dcooney** [comment]
EOD update:
- Updated both blocks to match @ravewebdev #84 style for passing props and defining `ALLOWED_BLOCKS` and `BLOCK_TEMPLATE`.
- Removed the block level `utils` directory from both blocks.
- Added some block options for color and initial load.
- Sent a PR (#86) to add global constants to the top level `src` directory. Linting errors are preventing that PR from passing. Something to do with my Prettier config.
- There is an issue accessing the `className` props in the `save` method that I have not been able to solve.

**Comment by dcooney** [comment]
EOD update
- Got config.js merged into `feature/block-2.0`
- Added options to 'Open First Item' and 'Toggle Others' in the Accordion Group.
![Screen Shot 2020-08-27 at 5 12 35 PM](https://user-images.githubusercontent.com/428624/91495466-93239380-e888-11ea-8030-29147ac2040d.png)

- Refactored `frontend.js` of the accordion block. Now imported as ES6 module into the main `frontend.js`. I could use a code review on this as I may have swayed too far from the WDS coding standards.
  - https://github.com/WebDevStudios/WDS-Blocks/blob/feature/Accordion-Block-%2378/src/frontend.js
  - https://github.com/WebDevStudios/WDS-Blocks/blob/feature/Accordion-Block-%2378/src/blocks/accordion/frontend/index.js
- Started working on Preview/Edit Mode styling of accordions.

**Comment by dcooney** [comment]
EOD Update
- Added new PR #87 to add the block category to the block plugin
- Updated naming of blocks
- `Accordion` block is no longer a public block and can ONLY be added to the `Accordions` block which is the parent
- Continued updating Edit styles and settings

**Comment by dcooney** [comment]
EOD Updates (Yesterday)
- Fixed JS linting errors
- Tried to squash many scss linting issues. May be something to do with my prettier config. I may park this for now.
- Continued work on edit/preview mode functionality

**Comment by salcode** [comment]
@dcooney 

I enjoyed the demo today in our team meeting - great stuff! One thing I noticed is the preview state and edit state look very similar. I think it is worth considering adding further visual indication of the different states.

**Comment by dcooney** [comment]
@salcode 
Agree on that. I've been trying to come up with a solution for this to make it more clear.

**Comment by dcooney** [comment]
EOD Update: 
- Continued work on edit-mode and styling.
- Started work on text color settings.

**Comment by dcooney** [comment]
EOD Update
- Edit mode styles updates
- Accordions and options now fully functional in Preview Mode
- Tomorrow we solve the background/text color options.

**Comment by dcooney** [comment]
EOD Update
- Added color options for text and background.
  - Still some thinking to do around theming/styles these accordions.
- Tweaked the preview/edit mode styles a bit.
- Fixed up some JS linting issues.
- CSS lint issues remain around `__` in CSS classnames
